config/routes.rb
SchoolClosing::Application.routes.draw do

  get "compare/show"

  match "/compare/:id" => "compare#show"
  
  resources :schools, :only => [:show]
  resources :compare, :only => [:show]

  get "about/index"
  match '/templates/compare.html', :to => redirect('/templates/compare.html')

  root :to => "home#index"
end

app/views/partials/_footer.es.html.erb
<div id="footer">
	<div id="footer-content">
	    <div id="footer-primary">
        <h2>Acerca de este proyecto</h2>
        <p>Este sitio web presenta datos provenientes de diversas fuentes, como el <a href="http://cps.edu">Sistema de escuelas públicas de Chicago</a>, la <a href="http://isbe.state.il.us">Junta estatal de educación de Illinois</a> y el <a href="http://uei.uchicago.edu/">Instituto de educación urbana de la Universidad de Chicago</a>. Nuestro objetivo es ayudar a las familias que tienen hijos en edad escolar, a otros residentes de Chicago y a los encargados de la elaboración de políticas, a acceder y comprender los datos que les ayudarán a tomar decisiones informadas sobre el futuro de las escuelas públicas.</p>
        <p><a href=<%= about_index_path%>> Conozca más sobre el proyecto &raquo;</a></p>
        <p><a href="http://goo.gl/LSJLx">Ver los datos utilizados en este proyecto &raquo;</a></p>
	    </div>
	    
	    <div id="footer-secondary">
	        <h2>Colaboradores</h2>        
	        <ul class="collaborators">
	            <li><a href="http://twitter.com/JMOChicago">Jeanne Marie Olson</a>, <a href="http://cpsapples2apples.wordpress.com">Apples 2 Apples</a></li>
	            <li><a href="http://twitter.com/shua123">Josh Kalov</a>, <a href="http://cpsapples2apples.wordpress.com">Apples 2 Apples</a></li>
	            <li><a href="http://www.linkedin.com/in/ljchandler">Lincoln Chandler</a></li>
	            <li><a href="http://twitter.com/_amtamayo">Anna Marie-Tamayo</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	            <li><a href="http://twitter.com/elnazem">Elnaz Moshfeghian</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	            <li><a href="http://twitter.com/PaulBaker">Paul Baker</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	            <li><a href="http://twitter.com/rougeux">Nick Rougeux</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	        </ul>
	    </div>
	</div>
    
    <div class="clear"></div>
</div>

app/views/partials/_footer.html.erb
<div id="footer">
	<div id="footer-content">
	    <div id="footer-primary">
        <h2>About this project</h2>
	        <p>This website presents data from several sources, including the <a href="http://cps.edu">Chicago Public Schools</a>, the <a href="http://isbe.state.il.us">Illinois State Board of Education</a>, and the <a href="http://uei.uchicago.edu/">University of Chicago Urban Education Institute</a>. Our goal is to help families with school children, other Chicago residents, and policy makers access and understand data that will help make informed decisions about the future of public schools.</p>
          <p><a href=<%= about_index_path%>> Learn more about the project &raquo;</a></p>
	        <p><a href="http://goo.gl/LSJLx">View data used in this project &raquo;</a></p>
	        <p><a href="https://github.com/amtamayo/schoolcuts">View the source code for this project &raquo;</a></p>
	    </div>
	    
	    <div id="footer-secondary">
	        <h2>Collaborators</h2>        
	        <ul class="collaborators">
	            <li><a href="http://twitter.com/JMOChicago">Jeanne Marie Olson</a>, <a href="http://cpsapples2apples.wordpress.com">Apples 2 Apples</a></li>
	            <li><a href="http://twitter.com/shua123">Josh Kalov</a>, <a href="http://cpsapples2apples.wordpress.com">Apples 2 Apples</a></li>
	            <li><a href="http://www.linkedin.com/in/ljchandler">Lincoln Chandler</a></li>
	            <li><a href="http://twitter.com/_amtamayo">Anna Marie-Tamayo</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	            <li><a href="http://twitter.com/elnazem">Elnaz Moshfeghian</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	            <li><a href="http://twitter.com/PaulBaker">Paul Baker</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	            <li><a href="http://twitter.com/rougeux">Nick Rougeux</a>, <a href="http://odi-chicago.org/">Open Data Institute</a></li>
	        </ul>
	    </div>
	</div>
    
    <div class="clear"></div>
</div>