config/routes.rb
SchoolClosing::Application.routes.draw do

  get "compare/show"

  match "/compare/:id" => "compare#show"
  
  resources :schools, :only => [:show]
  resources :compare, :only => [:show]

  get "about/index"
  match '/templates/compare.html', :to => redirect('/templates/compare.html')

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	include_status = [1,2,3,4,5,6,7]
  	@schools = School.where("closing_status> 0 or receiving_status in (1, 2)").sort_by{ |s| s.short_name } 
  	@students_affected = @schools.map{|s| s.enrollments_for_year(2012)}.inject{|sum,x| sum + x}
  	@receiving_schools = School.where("receiving_status = 1").sort_by{|s| s.short_name }
  	
  	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_detailed_look.es.html.erb
<h2>Una mirada detallada de las escuelas de la lista</h2>

<p>Los datos que están a continuación ayudan a comprender mejor cada escuela.</p>

<dl class="examples">
    <dt><img alt="" src="/images/isat.jpg" /> Desempeño en la evaluación ISAT por cohorte</dt>
    <dd>
        <p>Se registra el porcentaje de estudiantes que cumplen con o exceden los estándares estatales en las evaluaciones estandarizadas para un grupo o cohorte de estudiantes desde los grados 3º a 8º. Esto muestra cómo un conjunto específico de estudiantes se desempeñó con el correr de los años. </p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'King', school_path(59) %></p>
    </dd>
    
    <dt><img alt="" src="/images/5essentials.jpg"/> Tendencias de 5Essentials</dt>
    <dd>
        <p>Una evaluación de la capacidad de una escuela para tener éxito, basada en el contenido educativo, el entorno escolar, la participación de la familia, la colaboración de los docentes y el liderazgo eficaz, de acuerdo con lo establecido por la Universidad de Chicago.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Pershing West', school_path(94) %></p>
    </dd>
    
    <dt><img alt="" src="/images/probation.jpg"/> Tendencias en la situación de prueba</dt>
    <dd>
        <p>Cada año, el CPS evalúa a las escuelas para determinar si deberían estar en período de prueba y apuntar a cumplir con las medidas de mejoramiento. Las escuelas que están en período de prueba tienden a tener más cambios en el liderazgo, creando un entorno menos estable de aprendizaje.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Marconi', school_path(71) %></p>
    </dd>
    
    <dt><img alt="" src="/images/mobility.jpg" /> Tendencia en el índice de movilidad</dt>
    <dd>
        <p>El índice de movilidad mide cuántos estudiantes se trasladan a una escuela o fuera de una escuela, en un momento diferente al inicio o fin del año escolar. Cuando una escuela tiene un alto índice de movilidad es más difícil indicar si la escuela está progresando o no.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Lawrence', school_path(65) %></p>
    </dd>
    
    <dt><img alt="" src="/images/enrollment.jpg" /> Tendencias de inscripción</dt>
    <dd>
        <p>La cantidad de estudiantes que asisten a la escuela, medida el  día 20 de cada año escolar. Se utiliza para determinar las necesidades futuras de espacio, personal, equipos, etc.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Crown Community', school_path(22) %></p>
    </dd>
</dl>

app/views/home/_detailed_look.html.erb
<h2>A detailed look at schools on the list</h2>

<p>The following data helps better understand each school. </p>

<dl class="examples">
    <dt><img alt="" src="/images/isat.jpg" /> ISAT performance by cohort</dt>
    <dd>
        <p>The percent of students meeting or exceeding state standards on standardized tests is tracked for one group, or cohort, of students from grades 3&mdash;8. This shows how a specific set of students performed over time. </p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'King', school_path(59) %></p>
    </dd>
    
    <dt><img alt="" src="/images/5essentials.jpg"/> 5Essentials trends</dt>
    <dd>
        <p>An evaluation of a school’s ability to be successful, based on instructional content, school environment, family involvement, teacher collaboration, and effective leadership, according to The University of Chicago.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Pershing West', school_path(94) %></p>
    </dd>
    
    <dt><img alt="" src="/images/probation.jpg"/> Probation status trends</dt>
    <dd>
        <p>Each year CPS evaluates schools to determine if they should be placed on probation and targeted for improvement measures. Schools on probation tend to have more leadership changes, creating a less stable learning environment.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Marconi', school_path(71) %></p>
    </dd>
    
    <dt><img alt="" src="/images/mobility.jpg" /> Mobility rate trends</dt>
    <dd>
        <p>Mobility rate measures how many students transfer into, or out of, the school at times other than the beginning or end of a school year. When a school has a high mobility rate, it is more difficult to tell whether a school is making progress.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Lawrence', school_path(65) %></p>
    </dd>
    
    <dt><img alt="" src="/images/enrollment.jpg" /> Enrollment trends</dt>
    <dd>
        <p>This is the number of students attending the school, taken on the 20th day of each school year. It is used to determine future needs for space, personnel, equipment, etc.</p>
        <p class="mute"><%= I18n.t(:left) %>: <%= link_to 'Crown Community', school_path(22) %></p>
    </dd>
</dl>

app/views/home/_intro.es.html.erb
<div id="intro">
    <h1><%= number_with_delimiter(@students_affected, :delimiter => ',') %> estudiantes se verán afectados por los cierres de escuelas</h1>
    <p>El sistema de Escuelas Públicas de Chicago (CPS) ha marcado a <strong><%= @schools.count %> escuelas primarias</strong> para su cierre o consolidación basándose en la utilización, el desempeño y las opiniones de la comunidad. Cerrar una escuela es una decisión muy complicada, que afecta los resultados de los estudiantes, la confianza de los padres y la estabilidad del vecindario. Además de mostrar los datos que utiliza el CPS, este sitio web apunta a ayudar a los líderes de la escuela, los padres y las comunidades a saber más acerca de las escuelas que van a cerrarse y las oportunidades disponibles.</p>

    <div class="clear"></div>
</div>

app/views/home/_intro.html.erb
<div id="intro">
    <h1><%= number_with_delimiter(@students_affected, :delimiter => ',') %> students will be affected by school closings</h1>
    <p>Chicago Public Schools (CPS) has marked <strong><%= @schools.count %> elementary schools</strong> for closure or consolidation based on utilization, performance, and community feedback. Closing a school is a very disruptive decision, affecting student outcomes, parental confidence, and neighborhood stability. In addition to showing the data being used by CPS, this website aims to help school leaders, parents, and communities learn more about the schools being closed, and what options may be available.</p>

    <div class="clear"></div>
</div>

app/views/home/_schools_affected.es.html.erb
<h2><%= @schools.size.to_s %> <%= @schools.size > 1 ? " escuelas están afectadas" : " escuela está afectada" %></h2>

app/views/home/_schools_affected.html.erb
<h2><%= @schools.size.to_s %> <%= @schools.size > 1 ? " schools are" : " school is" %> affected </h2>

app/views/home/index.html.erb
<!-- Content -->
<div class="content">
  <%= render 'intro' %>
  <%= render 'schools_affected' %>

  <ul class="school-filters">
    <li><strong><%= I18n.t(:filter_by) %>:</strong></li>
    <li><a class="selected flag-all" href="#" data-filter="*"><%= I18n.t(:all) %></a></li>
    <li><a class="flag-closing" href="#" data-filter=".closing"><%= I18n.t(:closing) %></a></li>
    <li><a class="flag-turnaround" href="#" data-filter=".turnaround"><%= I18n.t(:turnaround) %></a></li>
    <li><a class="flag-relocating" href="#" data-filter=".relocating"><%= I18n.t(:relocating) %></a></li>
    <li><a class="flag-co-locating" href="#" data-filter=".co-locating"><%= I18n.t(:colocating) %></a></li>
    <li><a class="flag-closing-grades-9-to-11" href="#" data-filter=".closing-grades-9-to-11"><%= I18n.t(:closing_9_11) %></a></li>
    <li><a class="flag-receiving" href="#" data-filter=".receiving"><%= I18n.t(:receiving) %></a></li>
    <li><a class="flag-phasing-out-over-2-years" href="#" data-filter=".phasing-out-over-2-years"><%= I18n.t(:phasing_out)%></a></li>
  </ul>

  <div class="clear"></div>

  <div class="schools" id="names">
    <ol>
      <% @schools.each do |school| %> 
        <li class='<%="#{school.closing_status_name.gsub(' ','-')} #{school.receiving_status_name}" %>' >
          <%= link_to school.short_name, school_path(school) %>
          <span <%= (school.closing_status.nil? || school.closing_status == 0) ? "" : 
            "class=flag-#{school.closing_status_name.gsub(' ','-')}" %>>
            <%= (school.closing_status==0) ? "" : school.closing_status_name %>
          </span>
          <span <%= school.receiving_status.nil? ? "" : "class=flag-#{school.receiving_status_name}" %>>
            <%= school.receiving_status_name %>
          </span>
        </li>
      <% end %>
    </ol>

  </div>

  <hr />
  <script src="/scripts/jquery.isotope.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    $(function(){
      var $container = $("#names ol");

      $container.isotope({
      itemSelector: "li",
      layoutMode: 'fitColumns'
    });


    $('.school-filters a').click(function(){
      $(".school-filters a").removeClass("selected");
      $(this).addClass("selected");
      var selector = $(this).attr('data-filter');
      $container.isotope({ filter: selector });
      return false;
    });
          });
  </script>
  <%= render 'detailed_look' %>
  <div class="clear"></div>
</div>
<!-- /Content -->

