config/routes.rb
SchoolClosing::Application.routes.draw do

  get "compare/show"

  match "/compare/:id" => "compare#show"
  
  resources :schools, :only => [:show]
  resources :compare, :only => [:show]

  get "about/index"
  match '/templates/compare.html', :to => redirect('/templates/compare.html')

  root :to => "home#index"
end

app/models/school.rb
class School < ActiveRecord::Base
attr_accessible :access_type, :community_area, :cps_id, :full_name, :latitude, :level, :longitude, :phone, :school_type, :short_name, :street_address, :zip, :isat_url, :closing_status, :receiving_status
  
  has_many :enrollments
  has_many :essentials
  has_many :isat_scores
  has_many :map_legends
  has_many :mobilities
  has_many :probations
  has_many :races
  has_many :utilizations
  has_many :demographics
  has_many :school_addresses
  has_many :school_actions
  has_one :performance_metric

  def enrollments_for_year(number)
    enrollment = enrollments.select('count').where({
      :year_from => number
    })
    enrollment.empty? ? 0 : enrollment.first.count
  end

  def enrollment_totals
    enrollments.select('count').order('year_from').map(&:count).to_json
  end

  def ideal_capacity_for_year(number)
    utilizations.select('ideal_capacity').where({
      :year_from => number
    }).first.ideal_capacity
  end

  def first_enrollment_year
    enrollments.select('year_to').order('year_to').limit(1).first.year_to
  end
  
  def current_empty_seats(year)
  	ideal_capacity_for_year(year) - enrollments_for_year(year)
  end 
  # empty seat - if relocating use the ideal capacity for the new building
  def proposed_empty_seats(year)
  	if self.is_relocating?
  		relocation = SchoolAction.find_by_result_id(self.id)
  		relocation_school = School.find_by_id(relocation.school_id)
  		relocation_school.ideal_capacity_for_year(year) - enrollments_for_year(year)
  	else
  		ideal_capacity_for_year(year) - enrollments_for_year(year)
  	end
  end
  
  def scores_for(subject)
  	self.isat_scores.select{|s| s.subject.downcase == subject.downcase }
  end
  
  def reading
  	@scores = scores_for("reading")
  	@scores
  end
  
  def science
  	@scores = scores_for("science")
  	@scores
  end
  
  def math
  	@scores = scores_for("math")
  	@scores
  end
  
  def closing_status_name
    action = Action.find_by_action_code(closing_status)
    action ? action.name : ""
  end
  
  def receiving_status_name
    @receiving_status_name ||= self.receiving_status.nil? ? "" : "receiving"
  end
  
  def students_per_homeroom(year)
  	@result=nil
  	if (self.school_type.include? "Special Ed")
      @result=nil 
    else
	  	@homerooms = self.utilizations.select{ |u| u.year_from==year}.first.homerooms
	  	@enrollment = self.enrollments.select{ |e| e.year_from==year}.first.count
	  	
	  	if (@homerooms.nil? || @homerooms==0)
	  		@result = nil
	  	else
	  		@result = (@enrollment / @homerooms).to_i
	  	end
  	end
  	@result
  end
    
  def is_receiving?
    self.receiving_status == 1 || self.receiving_status == 2
  end 
   
  def is_closing?
  	self.closing_status == 1
  end
  
  def is_turnaround?
  	self.closing_status == 2
  end
  
  def is_relocating?
    self.closing_status == 3
  end
  
  def is_colocating?
  	self.closing_status == 4
  end
  
  def is_program_closure?
  	self.closing_status == 5
  end
  
  def is_phaseout?
  	self.closing_status == 6
  end
  
  def is_special_turnaround?
  	self.closing_status == 7
  end
   
  def receiving_schools
  	@receiving_schools = self.school_actions.map{|r| if(r.action_id==2 || r.action_id==7) then  r.result_id end}.uniq.join(", ")
  end
  
  def receiving_school_names
	@receiving_school_names = self.school_actions.map{|r| if(r.action_id==2 || r.action_id==7) then  School.find_by_id(r.result_id).short_name end}
  end
  
  def receiving_school_links
	@receiving_school_links = self.school_actions.map{|r| if(r.action_id==2 || r.action_id==7) then  "/schools/" + r.result_id.to_s end}
  end

  def colocating_schools
   @colocating_schools = self.school_actions.map{|r| if(r.action_id==5) then  r.result_id end}.uniq.join(", ")
  end
  
  def sending_schools
  	@sending_schools = SchoolAction.where("result_id=" + self.id.to_s + "").map{|sa| if(sa.action_id==2 || sa.action_id==7) then sa.school_id end }.uniq.join(",")
  end 
  
  def sending_school_names
	@sending_school_names = SchoolAction.where("result_id=" + self.id.to_s + "").
		map{|sa| if(sa.action_id==2 || sa.action_id==7) then School.find_by_id(sa.school_id).short_name end }
  end
  
  def sending_school_links
	@sending_school_links = SchoolAction.where("result_id=" + self.id.to_s + "").
		map{|sa| if(sa.action_id==2 || sa.action_id==7) then "/schools/" + sa.school_id.to_s end }
  end
  
  def is_higher_performing?(other_school)
  
  	@score = 0
  	if self.performance_metric.policy_points > other_school.performance_metric.policy_points 
  		@score = @score + 1
  	end
    if self.performance_metric.isat_composite > other_school.performance_metric.isat_composite
  		@score = @score + 1
  	end
	if self.performance_metric.value_added_reading > other_school.performance_metric.value_added_reading
		@score = @score + 1
	end

	if self.performance_metric.value_added_math > other_school.performance_metric.value_added_math
		@score = @score + 1
	end
  
  	self.level < other_school.level ||  @score > 2  		  		
  end 
  
  def new_building(format)
  	@result = nil 
  	@new_building_school_id = -1
  	@new_building_school_name = ""
  	@new_building_school_link = "#"
  	
  	if(self.school_actions.size > 0 && !self.school_actions.find_by_action_id(4).nil?)
  		@new_building_school_id = self.school_actions.find_by_action_id(4).result_id
  		@new_building_school_name = School.find_by_id(@new_building_school_id).short_name
  		@new_building_school_link = "/schools/" + @new_building_school_id.to_s
  	end
  	
  	case format
  		when "id"
  			@result = @new_building_school_id
  		when "name"
  			@result = @new_building_school_name
  		when "link"
  			@result = @new_building_school_link
  	end 
  	
	@result
  end
  
end

app/models/school_action.rb
class SchoolAction < ActiveRecord::Base
  attr_accessible :action_id, :result_id, :school_id, :result_code
  
  has_one :school
  belongs_to :result, :class_name => "School", :foreign_key => "result_id"
  belongs_to :receiving_action
  belongs_to :action
  
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])
    @year = 2012
    @enrollment = @school.enrollments_for_year(@year)
    @ideal_capacity = @school.ideal_capacity_for_year(@year)
    @first_enrollment_year = @school.first_enrollment_year
    @enrollment_totals = @school.enrollment_totals

    @address = @school.school_addresses.where('year_from=2012').first.address
  	@latitude = @address.latitude
  	@longitude = @address.longitude
  	
  	@status_with_transition_links = [1,2,3,4,6,7]
  	
  	utilization_rate = @enrollment.to_f / @ideal_capacity * 100
    
    case utilization_rate 
	    when 0..80
	    	@utilization_status = "Underutilized"
		  when 80..120
		    @utilization_status = "Efficient"
		  when utilization_rate > 120
        @utilization_status = "Overcrowded"
		  else
        @utilization_status = "Overcrowded"
	  end
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cps_id %><br />
    <%= f.text_field :cps_id %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :community_area %><br />
    <%= f.text_field :community_area %>
  </div>
  <div class="field">
    <%= f.label :school_type %><br />
    <%= f.text_field :school_type %>
  </div>
  <div class="field">
    <%= f.label :access_type %><br />
    <%= f.text_field :access_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/_highcharts_show.es.html.erb
<script>
$(function () {
	var enrollment_chart, isat_chart, mobility_chart, race_chart;
    $(document).ready(function() {
    	//ENROLLMENT CHART
        enrollment_chart = new Highcharts.Chart({
            chart: {
                renderTo: 'chart-enrollment',
                type: 'line'
            },
            credits: { enabled: false },
            legend: { enabled:false },
            plotOptions: {
	            line: {
	            	marker: {
		            	lineColor: "#fff",
		            	lineWidth: 1.5,
		            	radius: 5
	            	},
		            shadow: false
	            }
            },
            series: [{
            	color: "#3b5cb2",
                name: 'Cantidad de estudiantes inscritos',
                data: <%= raw @enrollment_totals %>,
                pointStart: Date.UTC(<%= raw @first_enrollment_year %>, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            }],
            subtitle: { text: ''}, 
            title: { text: '' },
            tooltip: {
                formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                        Highcharts.dateFormat('%Y', this.x) +': '+ this.y;
                }
            },
            xAxis: {
            	gridLineColor: "#dfdfdf",
                gridLineWidth: 1,
            	plotBands: [{
	                color: '#FCFFC5',
	                from: Date.UTC(2010, 0, 0),
	                to: Date.UTC(2013, 0, 0)
                }],                
                tickLength: 0,
                type: "datetime"
            },
            yAxis: {
            	gridLineColor: "#dfdfdf",
            	min: 0,
            	labels: {
	            	formatter: function(){
		            	return this.value;
	            	}
            	},
            	lineWidth: 1,
            	tickLength: 0,
                title: {
                    text: 'Cantidad de estudiantes inscritos'
                }
            }
        });
        
        //ISAT CHART
        isat_chart = new Highcharts.Chart({
            chart: {
                renderTo: 'chart-isat',
                type: 'line'
            },
            credits: { enabled: false },
            /* 
            legend: {
            	borderWidth: 0,
            	itemWidth: 200,
            	symbolWidth: 40
            },*/	
            legend : {
	        	borderWidth: 0,
	        	itemWidth: 130,
	        	symbolWidth: 40
            },		
            plotOptions: {
	            line: {
	            	marker: {
		            	lineColor: "#fff",
		            	lineWidth: 1.5,
		            	radius: 4,
		            	symbol: "circle"
	            	},
	            	shadow: false
	            }
            },
            series: [{
                color: "#1F88EA",
                name: 'Lectura',
                data: <%= raw @school.reading.sort_by{|s| s.year_from}.collect{|s| s.percent}.to_json %>,
                pointStart: Date.UTC(<%= raw @school.reading.first.year_to.to_i %>, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            },/*
	        {
                color: "#1F88EA",
                name: 'Reading: CPS Average',
                dashStyle: "ShortDash",
                data: [53,58,58,70,73,83],
                pointStart: Date.UTC(2007, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            },*/			
            {
             	name: 'Matemáticas',
                color: "#9E241D",
                data: <%= raw @school.math.sort_by{|s| s.year_from}.collect{|s| s.percent}.to_json %>,
                pointStart: Date.UTC(<%= raw @school.math.first.year_to.to_i %>, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            },/*
	        {
             name: 'Math: CPS Average',
                color: "#9E241D",
                dashStyle: "ShortDash",
                data: [69,71,69,74,78,81],
                pointStart: Date.UTC(2007, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            },*/			
            {
             	name: 'Ciencias',
                color: "#A9B80D",
                data: <%= raw @school.science.sort_by{|s| s.year_from}.collect{|s| s.percent}.to_json %>,
                pointStart: Date.UTC(<%= raw @school.science.first.year_to.to_i %>, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year

            }/* ,{
             	name: 'Science: CPS Average',
                color: "#A9B80D",
                dashStyle: "ShortDash",
                data: ['',56,'','',73,''],
                pointStart: Date.UTC(2007, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            }*/			
            ],
            subtitle: { text: '' }, 
            title: { text: '' },
            tooltip: {
                borderColor: "#ccc",
                formatter: function() {
                	var s = "<strong>" + Highcharts.dateFormat('%Y', this.x) + "</strong>";
                	
                	$.each(this.points, function(i, point){
                		if (point.y > 0)
	                		s += "<br />" + point.series.name + ": " + point.y + "%";
                	});
                	
                	return s;
                },
                shared: true
            },
            xAxis: {
            	gridLineColor: "#dfdfdf",
                gridLineWidth: 1,
                tickLength: 0,
            	type: "datetime"
            },
            yAxis: {
            	gridLineColor: "#dfdfdf",
            	max: 100,
            	min: 0,
            	labels: {
	            	formatter: function(){
		            	return this.value + "%";
	            	}
            	},
            	lineWidth: 1,
            	tickLength: 0,
                title: {
                	style: { fontWeight: "normal" },
                    text: 'Estudiantes que cumplen con o exceden los estándares estatales'
                }
            }
        });
        
        //MOBILITY CHART
        mobility_chart = new Highcharts.Chart({
            chart: {
                renderTo: 'chart-mobility',
                type: 'line'
            },
            credits: { enabled:false },
            series: [
            {
            	color: "#3b5cb2",
                name: 'Índice de movilidad',
                data: <%= raw @school.mobilities.sort_by{|m| m.year_to }.map{|m| m.rate}.to_json %>, 
                pointStart: Date.UTC(<%= raw @school.mobilities.first.year_to.to_i %>, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            }, {
             	color: "#3b5cb2",
             	name: 'Índice de movilidad promedio del CPS',
             	dashStyle: "ShortDash",
                data: [26.6, 25.2, 24.8, 24.5, 24.4, 24.0, 26.8, 22.4, 23.3, 18.8, 18.7, 17.9, 18.3],
                pointStart: Date.UTC(2000, 1, 1),
                pointInterval: 365 * 24 * 3600 * 1000 //one year
            }
            ],
            legend: { 
	        	borderWidth: 0,
	        	itemWidth: 130,
	        	symbolWidth: 40
            },
            plotOptions: {
	            line: {
	            	marker: {
		            	lineColor: "#fff",
		            	lineWidth: 1.5,
		            	radius: 5,
		            	symbol: "circle"
	            	},
		            shadow: false
	            }
            },
            subtitle: { text: ''},
            title: { text: ''},
            tooltip: {
                formatter: function() {
                	var s = "<strong>" + Highcharts.dateFormat('%Y', this.x) + "</strong>";
                	
                	$.each(this.points, function(i, point){
                		if (point.y > 0)
	                		s += "<br />" + point.series.name + ": " + point.y + "%";
                	});
                	
                	return s;
                }, 
                shared: true
            },
            xAxis: {
            	type: "datetime",
                gridLineColor: "#dfdfdf",
                gridLineWidth: 1,
                tickLength: 0
            },
            yAxis: {
            	gridLineColor: "#dfdfdf",
            	min: 0,
            	labels: {
	            	formatter: function(){
		            	return this.value;
	            	}
            	},
            	lineWidth: 1,
            	tickLength: 0,
                title: {
                    text: 'Índice de movilidad'
                }
            }
        });
        
        //RACE CHART
    	race_chart = new Highcharts.Chart({
	            chart: {
	            	renderTo: 'race-chart',
	                type: 'bar'
	            },
	            credits: {enabled: false},
	            legend: { enabled: false },
	            plotOptions: {
	                bar: {
	                    borderWidth: 0,
	                    dataLabels: {
	                        enabled: true,
	                        formatter: function(){
		                        return Highcharts.numberFormat(this.y, 0) + "%";
	                        }
	                    },
	                    groupPadding: 0,
	                    shadow: false
	                }
	            },
	            series: [{
	                data: <%= raw @school.races.map{ |r| r.percent} %>
	            }],
	            title: { text: '' },
	            tooltip: { enabled: false },
	            xAxis: {
	                categories: <%= raw @school.races.map{ |r| r.ethnicity }.inspect %>,
	                tickLength: 0
	            },
	            yAxis: {
	            	gridLineWidth: 0,
	                labels: { enabled: false },
	                title: { text: '' }
	            }
	    });
	    
	    //Demographics
	    dem_chart = new Highcharts.Chart({
	            chart: {
	            	renderTo: 'demographic-chart',
	                type: 'bar'
	            },
	            credits: {enabled: false},
	            legend: { enabled: false },
	            plotOptions: {
	                bar: {
	                    borderWidth: 0,
	                    dataLabels: {
	                        enabled: true,
	                        formatter: function(){
		                        return Highcharts.numberFormat(this.y, 0) + "%";
	                        }
	                    },
	                    groupPadding: 0,
	                    shadow: false
	                }
	            },
	            series: [{
	                data: <%= raw @school.demographics.where('year_from = 2012').map{ |item| item.percent } %>
	            }],
	            title: { text: '' },
	            tooltip: { enabled: false },
	            xAxis: {
	                categories: <%= raw @school.demographics.sort_by{|d| d.year_from}.map{ | item | item.category }.uniq %>,
	                tickLength: 0
	            },
	            yAxis: {
	            	gridLineWidth: 0,
	                labels: { enabled: false },
	                title: { text: '' }
	            }
	    });

	    

    });
    
});

</script>

app/views/schools/_show_map.html.erb
<!-- Map Script Section -->
<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=false&v=3.14">
  </script>
  <script type="text/javascript">
    var map;
    var layerl0;
    
    function initialize() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: new google.maps.LatLng( <%= @address.latitude %>, <%= @address.longitude %>),
        zoom: 13,
        scrollwheel: false,
        minZoom: 13,
        maxZoom: 16
      });
      var style = [
        {
          featureType: 'all',
          elementType: 'all',
          stylers: [
            { saturation: -100 },
            { "gamma": 1.75 }
          ]
        }
      ];
      var styledMapType = new google.maps.StyledMapType(style, {
        map: map,
        name: 'Styled Map'
      });
      map.mapTypes.set('map-style', styledMapType);
      map.setMapTypeId('map-style');

        //var marker = new google.maps.Marker({
        //    position: new google.maps.LatLng( <%= @address.latitude %>, <%= @address.longitude %>),
        //    map: map,
        //    title: '<%= @school.short_name %>'
        //});
         
      var circleOptions = {
        strokeColor: "#4b58a6",
        strokeOpacity: 0.5,
        strokeWeight: 4,
        fillColor: "#4b58a6",
        fillOpacity: 0,
        map: map,
        center: new google.maps.LatLng( <%= @address.latitude %>, <%= @address.longitude %>),
        clickable: false,
        zIndex: -1,
        radius: 1610
      };
      var onefiveOptions = {
        strokeColor: "#a64b58",
        strokeOpacity: 0.5,
        strokeWeight: 4,
        fillColor: "#a64b58",
        fillOpacity: 0,
        map: map,
        center: new google.maps.LatLng( <%= @address.latitude %>, <%= @address.longitude %>),
        clickable: false,
        zIndex: -1,
        radius: 2415
      };
      
      var thisCPSid = <%= @school.cps_id %>
      onefiveRadiusCircle = new google.maps.Circle(onefiveOptions);
      searchRadiusCircle = new google.maps.Circle(circleOptions);
      var LocationColumn = "Latitude"

      var whereClause = "ST_INTERSECTS(" + "Latitude" + ", CIRCLE(LATLNG" + new google.maps.LatLng( <%= @address.latitude %>, <%= @address.longitude %>) + "," + 2415 + "))";
	  /*
function query(){
		  var queryStr = [];
		  queryStr.push("SELECT " + "'levelnum', 'Value Added Math Score'");
		  queryStr.push(" FROM "+"1z1-EA7NoUQwox20w4VpjfMd_oGJ15h_JWVzQ8OA");     
		  queryStr.push(" WHERE "+ whereClause);
		  var sql = encodeURIComponent(queryStr.join(" "));
		  console.log(sql);
		  //$.ajax({url: "https://www.googleapis.com/fusiontables/v1/query?sql="+sql+"&callback="+callback+"&key=AIzaSyBZmv4Q6UbEd83q1GXlm6su2tMpwa18yrQ", dataType:"jsonp"});
	  }
	  query();
    //console.log(isBetter(3, 70, 38, 0, 1));
*/    var test = 1 ;
	  var id = 307;
	  var closing_status = <%= @school.closing_status.nil? ? -1 : @school.closing_status %>;
    
	  var receiving_schools = [<%= (@school.receiving_schools().size > 0) ? @school.receiving_schools() : 0 %>];
    var colocating_schools = [<%= (@school.colocating_schools().size > 0) ? @school.colocating_schools() : 0 %>];
    var blue_schools = [<%= (@school.colocating_schools().size > 0) ? @school.colocating_schools() : 0 %>, <%= (@school.receiving_schools().size > 0) ? @school.receiving_schools() : 0 %>];
	  var sending_schools = [<%= (@school.sending_schools().size > 0) ? @school.sending_schools() : 0 %>];
	  var new_building = <%= @school.new_building("id")%>;
	  
	  console.log(new_building);

    var whereBoundary = ''
	  
    if (receiving_schools != 0)
    {
        whereBoundary = "'SchoolCuts ID' in ("+ receiving_schools +")"
    }
    else
    {
        whereBoundary = "'SchoolCuts ID' =  <%= @school.id %>"
    }
      
      layerBoundaries = new google.maps.FusionTablesLayer({
        query: {
          select: "col0\x3e\x3e1",
          from: "1u2jMELhnoivuc678nMUn23dIFZwiqAnADsZX2u0",
          where: whereBoundary
        },
        map: map,
        styleId: 2,
        templateId: 2
        });


      layerl0 = new google.maps.FusionTablesLayer({
        query: {
          select: LocationColumn,
          from: "1rwYoQj6HhxjrdFnCQ4wSHYx43ilxMdPjnusdkSc",
          where: whereClause
        },
        map: map,
        styleId: 2,
        templateId: 2,
        styles: [{ 				
        	where: "'SchoolCuts ID' in (" + blue_schools + ")",
          markerOptions: {
            iconName: "blu_blank"
          }
        },{       
        where: "'SchoolCuts ID' in (" + sending_schools + ")",
          markerOptions: {
            iconName: "red_blank"
          }
        },{ 
          where: "'SchoolCuts ID' =  <%= @school.id %>  AND 'ReceivingStatus' > 0",
          markerOptions: {
            iconName: "large_blue"
          }
        },{     
        where: "'SchoolCuts ID' =  <%= @school.id %>  AND col52\x3e\x3e0 in (1, 6)",
          markerOptions: {
            iconName: "large_red"
          }
        },{        
		    where: "'SchoolCuts ID' in (" + new_building + ")",
        	markerOptions: {
        		iconName: "ltblu_blank"
        	}	
        }]
      });

      layerThis = new google.maps.FusionTablesLayer({
        query: {
          select: LocationColumn,
          from: '1rwYoQj6HhxjrdFnCQ4wSHYx43ilxMdPjnusdkSc',
          where: "'SchoolCuts ID' =  <%= @school.id %>  AND col52\x3e\x3e0 in (2, 4, 5, 7)"
        },
        map: map,
        styleId: 4,
        templateId: 2
		  });
      
      
      
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    
    /*
    var thisLevel = <%= @school.level %>;
    var thisIsat = 76.2;
    var thisPolicyPts = 36;
    var thisValueMath = -0.3; 
    var thisValueReading = 0.8;
    
    function isBetter(level){
	    console.log(level);
    }
    
    
	    function isBetter(level, isat, policyPts, valueMath, valueReading){
    	var countTrue = 0;
    	
    	
    	if(thisLevel > level)
    		return 1;
    	
    	if(thisIsat < isat) 
    		countTrue++;	
    	if(thisPolicyPts < policyPts)
    		countTrue++;
    	if(thisValueMath < valueMath)
    		countTrue++;
    	if(thisValueReading < valueReading)
    		countTrue++;
    		
    	if(countTrue>=3) 
    		return 1;
    	else return 0;
    }

	function callback(json) {
	  MapsLib.handleError(json);
	  var data = json["rows"];
	  var template = "";
	
	  console.log(data[0][0]);
	}
	*/
  </script>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <tr>
    <th>Cps</th>
    <th>Short name</th>
    <th>Full name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Street address</th>
    <th>Community area</th>
    <th>School type</th>
    <th>Access type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.cps_id %></td>
    <td><%= school.short_name %></td>
    <td><%= school.full_name %></td>
    <td><%= school.latitude %></td>
    <td><%= school.longitude %></td>
    <td><%= school.street_address %></td>
    <td><%= school.community_area %></td>
    <td><%= school.school_type %></td>
    <td><%= school.access_type %></td>
    <td><%= link_to 'Show', school %></td>
  </tr>
<% end %>
</table>

<br />

app/views/schools/new.html.erb
<h1>New school</h1>

<%= link_to 'Back', schools_path %>